#!/bin/bash

export TRIVIS_ROOT="$(pwd)"
export TRIVIS_BUILD_TYPE="Release"
export TRIVIS_BUILD_DIR="$(pwd)/build-${TRIVIS_BUILD_TYPE}"
export TRIVIS_BUILD_TRIVIS_INEXACT=0
export TRIVIS_BUILD_TRIVIS_PATHFINDER=0
export TRIVIS_BUILD_TRIVIS_PLUS=0
export TRIVIS_BUILD_EXAMPLES=0
export TRIVIS_BUILD_PERFORMANCE=0
export TRIVIS_BUILD_MESH_OPTIM=0
